FROM golang:1.24.13-alpine3.22 AS build
WORKDIR /app

COPY go.mod ./
COPY . .

RUN go build -o /gateway ./cmd/gateway

FROM alpine:3.20
COPY --from=build /gateway /gateway
EXPOSE 8080
CMD ["/gateway"]